### ISSUE TITLE
Fork-n-Go Tool Lending Site

### ISSUE THREAD

**Issue by jlord** [jlord/hello-world#11]
Cause I started it forever ago...

**Comment by voltdatalab** [comment]
Hey, jlord, thanks for this! It will fit my project just fine! 

However, I am fairly new to Javascript, and I am struggling to see how could I have not one, but two such lists per page, , using one different Google Spreadsheet keys for each. Is that possible? My limited knowledge in JS is holding me back here. 

I think my problem is here, it will only accept one:

**document.addEventListener('DOMContentLoaded', function() {
	      var URL = "https://docs.google.com/spreadsheets/d/1x163DjA2qIiqNA4dcf4HJSO7xh5FJX-iiqi7X1lcZd8/pubhtml"
	      Tabletop.init( { key: URL, callback: drawToolBox, simpleSheet: true } )**

Appreciate any feedback. 

Once again, this is a bless!

**Comment by jlord** [comment]
Hi! You can definitely use two different spreadsheets for two Sheetsee items on a page. First example that comes to mine is my own site, I use 4 different spreadsheets (I have one extra Spreadsheet url listed I'm not using): https://github.com/jlord/jlord.github.io/blob/master/index.html#L122-L131

**Comment by voltdatalab** [comment]
Thanks, I will see to it. My project is live thanks to your code: http://passaralhos.voltdata.info 

It is about journalist's layoffs in Brazil, and its getting some traction. Put a reference to you in the footer. 

Thanks for this.

**Comment by jlord** [comment]
@voltdatalab Bummer about the layouts, but cool project!
