### ISSUE TITLE
wrong hyperlink for Mozilla Developer Network in code-life.md

### ISSUE THREAD

**Issue by Siddharaj6010** [jlord/hello-world#21]
Hello, I am new to github so dont know if I should write this in issue or not.

In code-life.md file, the hyperlink for Mozilla Developer Network is given as http://www.mdn.com/ instead of https://developer.mozilla.org. Just wanted to point it out. 
I found many useful links from this file. Thanks for that.

**Comment by serhatculhalik** [comment]
gr8

**Comment by bin456789** [comment]
Hyper-link for Eloquent JavaScript is also wrong.

**Comment by jlord** [comment]
@bin456789 whoops! fixed now :sparkles:
