### ISSUE TITLE
helloworld

### ISSUE THREAD

**Issue by tinalazy** [jlord/hello-world#29]

**Comment by qrdsyufo** [comment]
hello，world

**Comment by loudmouthts** [comment]
HELLO, WORLD I BEEN READING DAY AND NIGHT BUT CAN NOT MAKE ANY SENCE OUT OF 
THIS THING, NOW I KNOW THIRS NOTHING WRONG WITH THE PROGRAM IT'S JUST ME 
THE PROGRAM IS WORKING JUST FINE, I'M NOT WORKING RIGHT AS USRAL. THANK YOU!
