### ISSUE TITLE
MY LIFE AND LIVING

### ISSUE THREAD

**Issue by skylimitbid** [jlord/hello-world#57]
“We have to allow ourselves to be loved by the people who really love us, the people who really matter. Too much of the time, we are blinded by our own pursuits of people to love us, people that don't even matter, while all that time we waste and the people who do love us have to stand on the sidewalk and watch us beg in the streets! It's time to put an end to this. It's time for us to let ourselves be loved.

**Comment by smiley001** [comment]
;) you onley live once
