### ISSUE TITLE
Hello word

### ISSUE THREAD

**Issue by ginae19990** [jlord/hello-world#71]
Im trying to get access my account

**Comment by 210ToNy210** [comment]
If you don't remember your password try to reset it then confirm the confirmation email

**Comment by FastTrackApps** [comment]
مرحبا بالعالم الوسيع
هنا انا بحاول شرح وتمرير كيفية العمل , لأنه يصعب علي كل العرب يتفاعلون بحكم اللغة صعبة جداا
فأتمنا ان يكون هناك دعم لهذا المجتمع
وشكرا لكم جدا 
![11889432_493201050837996_4683170287309957745_n](https://cloud.githubusercontent.com/assets/6448267/9298267/7ce9d55c-44b4-11e5-8830-7d9d9d50dd8a.jpg)
