### ISSUE TITLE
Link needs to be updated on talks-i-love.md

### ISSUE THREAD

**Issue by lunitaire** [jlord/hello-world#72]
When clicking the No more unicorns link, it goes to a private video that cannot be viewed. However searching Youtube with that phrase lead to a video that is public at: https://www.youtube.com/watch?v=uLxpko00QKk

(ps The video is great. Thanks for the link!)

**Comment by lunitaire** [comment]
I forked, updated, and made a pull request for this issue. I hope that helps! :smiley:

**Comment by jlord** [comment]
Thanks for the PR!
